Document: sshfail2kml
Title: Debian sshfail2kml Manual
Author: <insert document author here>
Abstract: This manual describes what sshfail2kml is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sshfail2kml/sshfail2kml.sgml.gz

Format: postscript
Files: /usr/share/doc/sshfail2kml/sshfail2kml.ps.gz

Format: text
Files: /usr/share/doc/sshfail2kml/sshfail2kml.text.gz

Format: HTML
Index: /usr/share/doc/sshfail2kml/html/index.html
Files: /usr/share/doc/sshfail2kml/html/*.html
